apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-k8s
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
      - name: hello-k8s
        image: asruf/hello-k8s:v0.1.0
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        limits:
          # memory: "128Mi"
          # cpu: "500m"