apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-service
spec:
  type: NodePort
  selector:
    app: hello-k8s
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
